
package core.jee.employeemanagement;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeManagementWebService", targetNamespace = "http://employeemanagement.jee.core/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagementWebService {


    /**
     * 
     * @return
     *     returns java.util.List<core.jee.employeemanagement.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEmployees", targetNamespace = "http://employeemanagement.jee.core/", className = "core.jee.employeemanagement.GetAllEmployees")
    @ResponseWrapper(localName = "getAllEmployeesResponse", targetNamespace = "http://employeemanagement.jee.core/", className = "core.jee.employeemanagement.GetAllEmployeesResponse")
    public List<Employee> getAllEmployees();

    /**
     * 
     * @param arg0
     * @throws ServiceUnavailableException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "registerNewEmployee", targetNamespace = "http://employeemanagement.jee.core/", className = "core.jee.employeemanagement.RegisterNewEmployee")
    @ResponseWrapper(localName = "registerNewEmployeeResponse", targetNamespace = "http://employeemanagement.jee.core/", className = "core.jee.employeemanagement.RegisterNewEmployeeResponse")
    public void registerNewEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Employee arg0)
        throws ServiceUnavailableException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns core.jee.employeemanagement.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeById", targetNamespace = "http://employeemanagement.jee.core/", className = "core.jee.employeemanagement.GetEmployeeById")
    @ResponseWrapper(localName = "getEmployeeByIdResponse", targetNamespace = "http://employeemanagement.jee.core/", className = "core.jee.employeemanagement.GetEmployeeByIdResponse")
    public Employee getEmployeeById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
